Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
  
  config.vm.define "sonarqube" do |sonar|
    sonar.vm.box = "ubuntu/focal64"
    sonar.vm.hostname = "sonarqube"
    sonar.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 2
    end
    sonar.vm.provision "shell", path: "provision.sh"
    sonar.vm.network "private_network", ip: "192.168.56.30"
    sonar.vm.network "forwarded_port", guest: 9000, host: 9000
    sonar.vm.network "forwarded_port", guest: 5432, host: 5433
  end
end