Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
  config.vm.boot_timeout = 600
  
  config.vm.define "k3s-master" do |master|
    master.vm.box = "generic/ubuntu2004"
    master.vm.hostname = "k3s-master"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.gui = false
      vb.check_guest_additions = false
    end
    master.vm.provision "shell", path: "provision.sh"
    master.vm.network "private_network", ip: "192.168.56.40"
    master.vm.network "forwarded_port", guest: 6443, host: 6443
    master.vm.network "forwarded_port", guest: 80, host: 8084
    master.vm.network "forwarded_port", guest: 30500, host: 30500
  end
end