global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'linux-server'
    static_configs:
      - targets: ['192.168.56.50:9100']