Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    jenkins.vm.provision "shell", path: "provision.sh"
    jenkins.vm.network "private_network", ip: "192.168.56.20"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.network "forwarded_port", guest: 50000, host: 50000
  end
end